/**
 * Seed data for offline/demo mode.
 * Realistic reports distributed across Kaduna LGAs with coordinates,
 * transcripts, and varied statuses/languages.
 * Used when Supabase is not configured.
 */

export const SEED_REPORTS = [
  {
    id: 'seed-001',
    created_at: '2026-08-28T08:15:00Z',
    transcript: 'Mun ga wasu mutane suna raba kudi a wajen rumfar zabe ta makarantar firamare ta Kawo. Sun zo da jakunkuna biyu cike da takardun kudi.',
    audio_url: null,
    latitude: 10.5597,
    longitude: 7.4256,
    language: 'hausa',
    status: 'pending',
    category: 'voter_suppression',
    updated_at: '2026-08-28T08:15:00Z',
  },
  {
    id: 'seed-002',
    created_at: '2026-08-28T09:30:00Z',
    transcript: 'We observed that the card reader at Barnawa Ward 3 has been malfunctioning since 7am. Over 200 voters are still waiting in line. INEC officials have not provided a replacement.',
    audio_url: null,
    latitude: 10.4876,
    longitude: 7.4372,
    language: 'english',
    status: 'verified',
    category: 'logistics',
    updated_at: '2026-08-28T10:00:00Z',
  },
  {
    id: 'seed-003',
    created_at: '2026-08-28T10:45:00Z',
    transcript: 'An samu cece-kuce a rumfar zabe ta Rigasa saboda wasu matasa sun yi kokarin karbe akwatin zabe. Jami\'an tsaro sun isa wurin.',
    audio_url: null,
    latitude: 10.5361,
    longitude: 7.4006,
    language: 'hausa',
    status: 'flagged',
    category: 'voter_suppression',
    updated_at: '2026-08-28T11:00:00Z',
  },
  {
    id: 'seed-004',
    created_at: '2026-08-28T11:00:00Z',
    transcript: 'Reports of underage voters being allowed to vote at Zaria City polling unit 007. Multiple eyewitness accounts confirm at least 15 individuals without proper identification.',
    audio_url: null,
    latitude: 11.0801,
    longitude: 7.7069,
    language: 'english',
    status: 'pending',
    category: 'voter_suppression',
    updated_at: '2026-08-28T11:00:00Z',
  },
  {
    id: 'seed-005',
    created_at: '2026-08-28T11:30:00Z',
    transcript: 'Ana yada jita-jita a kafofin sada zumunta cewa an soke zaben a Kaduna ta Kudu. Wannan labari ne na karya. Zaben yana ci gaba a duk rumfunan zabe.',
    audio_url: null,
    latitude: 10.4500,
    longitude: 7.4500,
    language: 'hausa',
    status: 'flagged',
    category: 'voter_suppression',
    updated_at: '2026-08-28T12:00:00Z',
  },
  {
    id: 'seed-006',
    created_at: '2026-08-28T12:15:00Z',
    transcript: 'Polling unit at Sabon Tasha Primary School opened 2 hours late. Presiding officer arrived at 10:30am instead of 8:30am. Long queues forming outside.',
    audio_url: null,
    latitude: 10.4632,
    longitude: 7.4581,
    language: 'english',
    status: 'verified',
    category: 'logistics',
    updated_at: '2026-08-28T12:30:00Z',
  },
  {
    id: 'seed-007',
    created_at: '2026-08-28T13:00:00Z',
    transcript: 'Wani dan takara na jam\'iyyar adawa ya shigo rumfar zabe tare da magoya bayansa. Sun yi kokarin tsoratarwa ga masu zabe don su canza ra\'ayinsu.',
    audio_url: null,
    latitude: 10.6019,
    longitude: 7.4331,
    language: 'hausa',
    status: 'pending',
    category: 'voter_suppression',
    updated_at: '2026-08-28T13:00:00Z',
  },
  {
    id: 'seed-008',
    created_at: '2026-08-28T13:45:00Z',
    transcript: 'Confirmed: ballot papers for Igabi LGA Ward 5 have wrong serial numbers. INEC has dispatched replacements from the Kaduna central store. Voting suspended temporarily.',
    audio_url: null,
    latitude: 10.6500,
    longitude: 7.4800,
    language: 'english',
    status: 'verified',
    category: 'logistics',
    updated_at: '2026-08-28T14:00:00Z',
  },
  {
    id: 'seed-009',
    created_at: '2026-08-28T14:20:00Z',
    transcript: 'An lura da wasu barayin zabe suna amfani da na\'urar daukar hoto don yin rikodin yadda mutane suka zabi. An kama mutum biyu a rumfar zabe ta Tudun Wada.',
    audio_url: null,
    latitude: 10.5150,
    longitude: 7.4420,
    language: 'hausa',
    status: 'flagged',
    category: 'voter_suppression',
    updated_at: '2026-08-28T14:30:00Z',
  },
  {
    id: 'seed-010',
    created_at: '2026-08-28T14:50:00Z',
    transcript: 'Peaceful voting in progress at Kakuri Ward. Turnout estimated at 65%. No incidents reported. Observers from EU and AU present on site.',
    audio_url: null,
    latitude: 10.4780,
    longitude: 7.4450,
    language: 'english',
    status: 'verified',
    category: 'logistics',
    updated_at: '2026-08-28T14:50:00Z',
  },
  {
    id: 'seed-011',
    created_at: '2026-08-28T07:00:00Z',
    transcript: 'Early morning setup at Kaduna North LGA headquarters proceeding smoothly. All 42 polling units in the constituency have received materials.',
    audio_url: null,
    latitude: 10.5400,
    longitude: 7.4500,
    language: 'english',
    status: 'verified',
    category: 'logistics',
    updated_at: '2026-08-28T07:30:00Z',
  },
  {
    id: 'seed-012',
    created_at: '2026-08-28T15:10:00Z',
    transcript: 'Wasu yan sanda na tsayar da mutane a hanyar zuwa rumfar zabe a Narayi. Suna binciken motoci kuma suna juya wasu baya ba tare da dalili ba.',
    audio_url: null,
    latitude: 10.4950,
    longitude: 7.4100,
    language: 'hausa',
    status: 'pending',
    category: 'voter_suppression',
    updated_at: '2026-08-28T15:10:00Z',
  },
];

/**
 * Simulated API usage counters for the metric bar.
 */
export const SEED_API_METRICS = {
  transcription_calls: 847,
  transcription_limit: 1000,
  storage_used_mb: 234,
  storage_limit_mb: 500,
};
